name: bundle Persepolis Download Manager for linux
on:
  release:
    types: [published]
jobs:
  bundle-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
         sudo apt -y update
         sudo apt -y upgrade
         sudo apt -y install libxcb-cursor0 python3-pip
      - name: Install requirements
        run: pip install PySide6 requests setproctitle psutil yt-dlp pyinstaller
      - name: Download Aria2
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "aria2/aria2"
          latest: true
          fileName: "^.*-linux-.*$"
          extract: true
      - name: Download ffmpeg
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "BtbN/FFmpeg-Builds"
          latest: true
          fileName: "^.*-latest-linux64-gpl-.*$"
          extract: true
      - name: Download sthp
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "KaranGauswami/socks-to-http-proxy"
          latest: true
          fileName: "^.*-linux.*$"
          extract: true
      - name: Build
        run: pyinstaller -n "Persepolis Download Manager" -F --clean --windowed --add-binary "sthp:." --add-binary "aria2c:." --add-binary "ffmpeg:." persepolis/Persepolis\ Download\ Manager.py
