name: bundle Persepolis Download Manager for linux
on: workflow_dispatch
jobs:
  bundle-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
         sudo apt -y update
         # sudo apt -y upgrade
         sudo apt -y install python3-virtualenv libxcb-cursor0 libxcb-shape0 libxcb-xkb1 libxkbcommon-x11-0 libxcb-keysyms1 libxcb-icccm4 libxcb-shape0 python3-pip xz-utils unzip
      - name: Virtualenv
        run: | 
          virtualenv venv
          source venv/bin/activate
          deactivate
      - name: Install requirements
        run: |
            source venv/bin/activate
            pip install PySide6 PySide6-Addons requests setproctitle psutil yt-dlp pyinstaller
            deactivate
      - name: Download Aria2
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "q3aql/aria2-static-builds"
          latest: true
          fileName: "^.*-linux-gnu-64bit-build1.tar.bz2"
      - name: Download ffmpeg
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "BtbN/FFmpeg-Builds"
          latest: true
          fileName: "ffmpeg-master-latest-linux64-gpl.tar.xz"
      - name: Download sthp
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "KaranGauswami/socks-to-http-proxy"
          latest: true
          fileName: "^.*-linux"
      - name: Preparing Files
        run: |
          mv sthp-linux sthp
          tar -xf ffmpeg-master-latest-linux64-gpl.tar.xz ffmpeg-master-latest-linux64-gpl/bin/ffmpeg --strip-components 2
          tar -xvjf aria2-*-linux-gnu-64bit-build1.tar.bz2 --strip-components 1
          ls -lrth
      - name: Build
        run: |
          source venv/bin/activate
          pip freeze
          pyinstaller -n "Persepolis Download Manager" -F --clean --windowed --add-binary "sthp:." --add-binary "aria2c:." --add-binary "ffmpeg:." persepolis/Persepolis\ Download\ Manager.py
          ls dist -lrth
          deactivate
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: Archive build
          path: dist/Persepolis\ Download\ Manager
      - name: Test
        run: ./dist/Persepolis\ Download\ Manager --version
