name: bundle Persepolis Download Manager for windosw
on: workflow_dispatch
jobs:
  bundle-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: persepolisdm/persepolis
      - name: Install requirements
        run: pip install PySide6 requests pypiwin32 setproctitle psutil yt_dlp pyinstaller urllib3
